os: osx
osx_image: xcode12.2
language: go

branches:
  except:
    - main

git:
  depth: false
  quiet: true

go:
  - "1.14.x"

services:
  - docker

cache:
  directories:
    - $HOME/Library/Caches/Homebrew
    - /usr/local/Homebrew

before_cache:
  - brew cleanup
  - find /usr/local/Homebrew \! -regex ".+\.git.+" -delete

addons:
  homebrew:
    packages:
    - gsettings-desktop-schemas
    - hicolor-icon-theme
    - shared-mime-info
    - gtk+3
    - gtk-mac-integration
    - adwaita-icon-theme
    update: true
    
before_install:
  - "export DISPLAY=:99.0"
  - npm install --global appdmg

install:
  - make -C ci/ deps

script:
  - make -C ci/ clean-mac-bundle
  - travis_wait 45 make build-gui
  - travis_wait 45 make -C ci/ make-mac-bundle
  - travis_wait 45 make -C ci/ make-dmg
  - travis_wait 45 make -C ci/ make-gui-for-release

deploy:
  provider: releases
  api_key: $GH_DEPLOY_TOKEN
  file_glob: true
  file: release/*
  skip_cleanup: true
  on:
    tags: true
