# Gopkg.toml example
#
# Refer to https://golang.github.io/dep/docs/Gopkg.toml.html
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#   name = "github.com/x/y"
#   version = "2.4.0"
#
# [prune]
#   non-go = false
#   go-tests = true
#   unused-packages = true


[[constraint]]
  branch = "master"
  name = "github.com/TheCreeper/go-notify"

[[constraint]]
  branch = "main"
  name = "github.com/coyim/gosx-notifier"

[[constraint]]
  name = "github.com/godbus/dbus"
  version = "4.1.0"

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.6.0"

[[constraint]]
  name = "golang.org/x/text"
  version = "0.3.2"

[[constraint]]
  branch = "main"
  name = "github.com/coyim/gotk3osx"

[[constraint]]
  name = "github.com/xdg/stringprep"
  version = "1.0.0"

[[constraint]]
  branch = "master"
  name = "github.com/golang-collections/collections"

[[constraint]]
  branch = "master"
  name = "github.com/hydrogen18/stalecucumber"

[[constraint]]
  name = "github.com/prashantv/gostub"
  version = "1.0.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.7.0"
